languageCode = "en"
languageName = "English"
weight = 1

title = "Tomás Fernandes"

[params]
  displayName = "EN"
  isoCode = "en"
  mainSections = ["work"]
  rtl = false
  description = "Tomás Fernandes is a computer scientist and software engineer at Coinbase interested in software engineering, distributed systems, and geometric deep learning."
  dateFormat = "January 2006"

[author]
  name = "Tomás Fernandes"
  image = "img/author.jpeg"
  headline = "Computer Scientist & Software Engineer"
  bio = "Computer Scientist & Software Engineer"
  links = [
    { github = "https://github.com/tomasff" },
    { x-twitter = "https://twitter.com/tomasff02" },
    { linkedin = "https://www.linkedin.com/in/tomas-fernandes02/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  ]
