baseURL = 'https://tffr.net/'
languageCode = 'en-GB'
title = 'Tom치s Fernandes'
theme = 'tomas'

[markup.goldmark.renderer]
unsafe = true

[params]
description = 'Tom치s Fernandes is a computer scientist and software engineer at Coinbase interested in software engineering, distributed systems, and geometric deep learning.'
keywords = ['Tomas Fernandes', 'Tom치s Fernandes', 'personal website']

[params.author]
name = 'Tom치s Fernandes'
image = 'img/author.jpeg'
headline = 'Computer Scientist & Software Engineer'
links = [
    { github = 'https://github.com/tomasff' },
    { x-twitter = 'https://twitter.com/tomasff02' },
    { linkedin = 'https://www.linkedin.com/in/tomas-fernandes02/' },
]
