
name: Build and upload website artifacts

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

concurrency:
  group: "hugo-ipfs-deploy"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  ipfs-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0
      HUGO_ENVIRONMENT: production
      TZ: Europe/London
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build with Hugo
        run: hugo --minify
      - name: Upload build artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: public/*
          name: website.zip
